package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "windows",
    srcs = ["env.cc"],
    deps = [
        "//cub/env/time",
        "//cub/env/concurrent",
        "//cub/env/fs",
    ],
)
